# Generated by Django 5.2.1 on 2025-05-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Neurologista', 'Neurologista'), ('Pediatra', 'Pediatra')], null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='criado_em',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, help_text='Criado Em', verbose_name='Criado Em'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(help_text='Nº do conselho', max_length=12, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(help_text='Ex: 01/01/2000', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(help_text='Nome do médico', max_length=200, verbose_name='Nome Completo'),
        ),
    ]
