# Generated by Django 5.2.1 on 2025-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_alter_medico_options_medico_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Neurologista', 'Neurologista'), ('Pediatra', 'Pediatra')]),
        ),
    ]
